# Generated by Django 2.2 on 2019-10-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstest',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
